Document: tn5250
Title: Debian tn5250 Manual
Author: <insert document author here>
Abstract: This manual describes what tn5250 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tn5250/tn5250.sgml.gz

Format: postscript
Files: /usr/share/doc/tn5250/tn5250.ps.gz

Format: text
Files: /usr/share/doc/tn5250/tn5250.text.gz

Format: HTML
Index: /usr/share/doc/tn5250/html/index.html
Files: /usr/share/doc/tn5250/html/*.html
